server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: flight-admin
          uri: lb://flight-service
          predicates:
            - Path=/schedule/route, /schedule/inventory
          filters:
            - StripPrefix=1
            - JwtAuthFilter=ROLE_ADMIN

        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**, /ticket/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/