server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**, /ticket/**

        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flight/**, /airline/**, /search/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
