server:
  port: 9091

spring:
  application:
    name: flight-service

  datasource:
    url: jdbc:mysql://localhost:3306/flightdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
